# -*- coding: utf-8 -*-
"""codetest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYUlsmJALLHHxmdhD9He_nUz5P0wJy1T
"""

num = int (input("Digite um número: "))

res = num * num

print (res)